export enum SocketEvents {
    GETSONGREQUESTLIST = 'GETSONGREQUESTLIST',
    GETUSERSBYROOM = 'GETUSERSBYROOM',
    SENDMESSAGEROOM = 'SENDMESSAGEROOM',
    VOTESONGREQUEST = 'VOTESONGREQUEST',
    SELECTEDSONGREQUEST = 'SELECTEDSONGREQUEST',
    ERRORS = 'ERRORS',
}
